sudo: required
services:
  - docker

before_install:
  - docker build -t noalistic/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true noalistic/react-test npm test -- --coverage

after_success:
  # build docker images
  - docker build -t noalistic/ninostyle-client ./client
  - docker build -t noalistic/ninostyle-nginx ./nginx
  - docker build -t noalistic/ninostyle-server ./server
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these build images and push to docker hub
  - docker push noalistic/ninostyle-client
  - docker push noalistic/ninostyle-nginx
  - docker push noalistic/ninostyle-server
# deploy:
#   provider: elasticbeanstalk
#   region: us-east-2
#   app: ninostyle
#   env: Ninostyle-env
#   bucket_name: elasticbeanstalk-us-east-2-946065250109
#   bucket_path: docker-ninostyle
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: $AWS_SECRET_KEY
